### ISSUE TITLE
Is the v23 Tag Intentional

### ISSUE THREAD

**Issue by theory** [vertica/vertica-containers#46]
I see on Docker Hub that the latest tag, 16 days ago, is for [23.3.0-0](https://hub.docker.com/layers/vertica/vertica-ce/23.3.0-0/images/sha256-7e3ad209b730a8c767678f5471672542c30d92208d009918cf4c54830dc22c69?context=explore). Is that intentional? I thought the most recent version was 12.x.

**Comment by spilchen** [comment]
Yes, 23.3.0-0 is intentional. That is the new versioning scheme for Vertica to align with OpenText policy. The format is `<year>.<quarter>`. You can expect a 23.4.0-0 version to come out in October. Highlights for the 23.3.x version can be found in our official docs: https://docs.vertica.com/23.3.x/en/new-features/23.3/
